export enum PRODUCT_TYPE_VALUE {
  SUPPLIES = 'SUPPLIES',
  RAW_MATERUAL = 'RAW_MATERIAL',
  FINISHED_GOOD = 'FINISHED_GOOD',
  WORK_IN_PROGRESS = 'WORK_IN_PROGRESS',
}

export const PRODUCT_TYPE_LABEL = {
  [PRODUCT_TYPE_VALUE.SUPPLIES]: 'Supplies',
  [PRODUCT_TYPE_VALUE.RAW_MATERUAL]: 'Raw Material',
  [PRODUCT_TYPE_VALUE.FINISHED_GOOD]: 'Finished Good',
  [PRODUCT_TYPE_VALUE.WORK_IN_PROGRESS]: 'Work In Progress',
};

export const PRODUCT_TYPE_OPTIONS = [
  {
    id: 1,
    label: PRODUCT_TYPE_LABEL[PRODUCT_TYPE_VALUE.SUPPLIES],
    value: PRODUCT_TYPE_VALUE.SUPPLIES,
  },
  {
    id: 2,
    label: PRODUCT_TYPE_LABEL[PRODUCT_TYPE_VALUE.RAW_MATERUAL],
    value: PRODUCT_TYPE_VALUE.RAW_MATERUAL,
  },
  {
    id: 3,
    label: PRODUCT_TYPE_LABEL[PRODUCT_TYPE_VALUE.FINISHED_GOOD],
    value: PRODUCT_TYPE_VALUE.FINISHED_GOOD,
  },
  {
    id: 4,
    label: PRODUCT_TYPE_LABEL[PRODUCT_TYPE_VALUE.WORK_IN_PROGRESS],
    value: PRODUCT_TYPE_VALUE.WORK_IN_PROGRESS,
  },
];
